name: TrueDamageNullifier-v1.3
version: 1.3
main: com.sipilen.truedamagenullifier.TrueDamageNullifier
api-version: 1.16
commands:
  tdn:
    description: Управление модификаторами урона для игроков (включая IP-привязку по никам)
    usage: /<command> <disable|reduce|amplify|status|reload|list|clear|ipdisable|ipreduce|ipamplify|nickclear|nicklist> [player/nick] [time] [reason]
permissions:
  tdn.use:
    description: Базовое использование команды
    default: op
  tdn.admin:
    description: Полный доступ (reload, list, nicklist)
    default: op
  tdn.list:
    description: Просмотр списка модификаторов игроков
    default: op
  tdn.nicklist:
    description: Просмотр списка модификаторов по никам/IP
    default: op
  tdn.clear:
    description: Снятие модификаторов с игрока
    default: op
  tdn.nickclear:
    description: Снятие модификаторов по нику/IP (только консоль)
    default: op
  tdn.disable:
    description: Отключение урона для игрока
    default: op
  tdn.ipdisable:
    description: Отключение урона по нику/IP (только консоль)
    default: op
  tdn.reduce:
    description: Уменьшение урона для игрока
    default: op
  tdn.ipreduce:
    description: Уменьшение урона по нику/IP (только консоль)
    default: op
  tdn.amplify:
    description: Увеличение урона для игрока
    default: op
  tdn.ipamplify:
    description: Увеличение урона по нику/IP (только консоль)
    default: op
  tdn.status:
    description: Просмотр статуса урона игрока
    default: op